services:
  mongodb:
    image: mongo:7
    container_name: bokka-mongo
    ports:
      - "27017:27017"
    volumes:
      - bokka-mongo-data:/data/db
    restart: unless-stopped

volumes:
  bokka-mongo-data:
    external: true
