package com.example.demo.enums;

public enum CargoFuncionarioEnum {
    RECEPCIONISTA,
    SECRETARIA,
    AUXILIAR_SAUDE_BUCAL,
    AUXILIAR_DENTARIO,
    TECNICO_SAUDE_BUCAL,
    TECNICO_PROTESE_DENTARIA,
    TECNICO_RADIOLOGIA,
    AUXILIAR_ADMINISTRATIVO,
    ADMINISTRATIVO,
    SOCIO,
    COORDENADOR_CLINICO,
    GERENTE,
    FINANCEIRO,
    MARKETING,
    COMERCIAL,
    SERVICOS_GERAIS,
    SEGURANCA,
    ESTAGIARIO,
    OUTRO
}
